### PR TITLE
Language Edit

### PR DESCRIPTION
**Pull request by MWE001**
Changed a typo in lang_tour file.

### CODE REVIEW

**Comment by vendethiel** [comment]
BTW, is there a french translation of IM?

**Comment by vendethiel** [comment]
Or other templates.

**Comment by MWE001** [comment]
There was translations for 1.4.1 but not sure about 150. I got loads of templates for 150 as well. Not sure where I can put them due to no disc space left on my hosting account

**Comment by vendethiel** [comment]
I think you can upload them to github. Look at how MG's doing it: It could be IntegraMOD150Templates.

**Pull request merged**
