### PR TITLE
Page footer cahnges

### PR DESCRIPTION
**Pull request by MWE001**
Fixed copyright symbol (was showing as ?)

### CODE REVIEW

**Comment by IntegraMOD** [comment]
if your seeing this in fisubice then you have an older version. Im pretty much completely rebuilding fisubice so probably best not to commit changes to it for awhile

**Comment by MWE001** [comment]
Sorry about that. I must have. I was sure I was using the one I grabbed from here 2 days ago.

**Comment by IntegraMOD** [comment]
strange... yesterday I thought I commited a ton of changes but they are not here. Ill have to figure out why its not working

**Comment by MWE001** [comment]
I synced some files to one of my repos for another project and they were not saved. So I know how that goes.

Glad we found it out now rather than later.

**Comment by IntegraMOD** [comment]
my local copy shows it was merged to the master but it doesnt show up on github

**Comment by MWE001** [comment]
You using Desktop Git? I am and had the same exact issue. I tried the command promt Git once and it worked but Im not a cmd type of person. I like the desktop but it shafts me more than it helps me.

**Comment by IntegraMOD** [comment]
thats why I like tortoise SVN...lol

**Comment by MWE001** [comment]
Hmm not familiar

**Pull request merged**
