### PR TITLE
Feature/im151 beta version

### PR DESCRIPTION
**Pull request by vendethiel**
So; here is my version.

### CODE REVIEW

**Comment by vendethiel** [comment]
Fixed merge conflicts.

**Comment by vendethiel** [comment]
BTW, this is currently **untested**. I need to try it more. But later :)

**Comment by MWE001** [comment]
Well let me know one way or the other. I can not as of right do any file changes at all. We are on two different versions/file systems now. I will wait until you test to merge pull request and get back started again. I have not had time to work on this. I am still trying to get images to show up in Full Album Pack  in Integra 1.4.1 and Been working on both of my Icy websites the last few days.

**Comment by vendethiel** [comment]
Technically you can. Go to my profile > repositories > IntegraMOD150 > click "master" > select the branch (it's at the top of this page) > click download.

But anyway I just need to finish few things before doing testing (8am here)

**Comment by vendethiel** [comment]
So... It seems I can't change the design anymore. I need to see what's going on...

**Comment by vendethiel** [comment]
There's a really annoying "mobile bar" at the top. @IntegraMOD Do you remember this? Do you think I can remove it (or at least hide it with a media query)?

**Comment by vendethiel** [comment]
Should be good to go. Or at least to test :-).

 - Fixed dload.php
 - Fixed statistics
 - Fixed the cash menu separators
 - Fixed the cash menu sections
 - Fixed mobile detection

**Comment by vendethiel** [comment]
BTW @MWE001 , Do note I cannot merge by myself. So I'll need your approval anyway.

**Comment by MWE001** [comment]
Duly noted =)

**Comment by vendethiel** [comment]
That was fast :D. Please try it out and tell me if you find bugs!

**Comment by MWE001** [comment]
Sorry haven't been much help lately. When my net went down I got behind on what I had already started working on for Icy Phoenix. I had to get back on track. I have been fiddling with IM here and there as things come up that are similar between the two CMS systems. One stop fix all but fixes both systems for certain things.

**Comment by MWE001** [comment]
I'll give it a go here in a short bit. I need to clean up my WAMP server. it literally has no less than 25 projects on it and it is all becoming way to much  lol. Time for a winter cleanup before anymore projects get added to it.

**Comment by vendethiel** [comment]
I do the same regularly! The other issue is keeping project "synchronized" between computers...

**Comment by vendethiel** [comment]
Also take your time. I just wrote here because I saw you on the IP forums :-)

**Comment by MWE001** [comment]
Yeah I'm going to be busy today with integra/Icy. I am tired as can be but forced to stay awake to go get the boy from work later. 

On a side note, I got a couple mods I want to try to bring up to date for Integra as well and maybe port one over to icy if I can figure it out.

**Comment by vendethiel** [comment]
Alright, you know how to open issues :-).

**Comment by MWE001** [comment]
Oh Yeah I am much better at opening issues than closing them  =)

**Comment by vendethiel** [comment]
It's fine! I wish I could be thorough so issues needn't be opened to start with...

**Comment by MWE001** [comment]
We all miss things man. One little slip of the finger and we forget a ; and all the code breaks and throws errors or what ever. it just happens. That's what we have beta testers for lol to find our errors.

**Pull request merged**
