### PR TITLE
Fix for recent PHP versions

### PR DESCRIPTION
**Pull request by vendethiel**
Hey @MWE001,

I know IntegraMOD is a big part of your commitment to forum.
So I took the liberty of fixing the bugs introduced by recent PHP versions.

Consider it payback for the help you've provided by finding bugs on IP :-).

### CODE REVIEW

**Comment by vendethiel** [comment]
:-)

**Comment by vendethiel** [comment]
Feel free to post about it [here](http://mail.integramod.com/forum/viewtopic.php?f=12&p=40536#p40536)

I don't have an account, and it doesn't seem like I can create one.

**Comment by MWE001** [comment]
Thanks! I'll give it a go and see what happens. No payback was necessary. I love working on websites. I am not that good at it but it gives me something to do to occupy my time. As for helping at Icy, well, lol, I know I have been sort of a PITA a shade bit, but hope a few fixes I came up with work.

**Comment by vendethiel** [comment]
Rather the opposite. You've been really helpful, I feel bad you stumble upon bugs as much.

**Pull request merged**
