### PR TITLE
Use new PHP variables, remove PHP3.x/4.x interop code

### PR DESCRIPTION
**Pull request by vendethiel**
- removed the `phpversion()` that compared against PHP 4.x or 3.x
- removed old-style $HTTP_x_VARS
- removed the $ini_val() stuff

### CODE REVIEW

**Comment by vendethiel** [comment]
@IntegraMOD I started working on integating you guys' changes. But it's pretty huge :).

**Comment by vendethiel** [comment]
@IntegraMOD Just a question - in your version; you removed Keep Unread Flags. May I ask why.

**Comment by vendethiel** [comment]
This approach is actually the wrong one. I'll go back to the version @IntegraMOD uploaded, and put the commits @MWE001 and I have done on top.

**Comment by MWE001** [comment]
Yeah there is a lot of work there. That is why it is only for fun for me. Work a while go find something else to do for a while. Good times!

**Comment by vendethiel** [comment]
Are you fine with what I said?

This repository says it's running IntegraMOD1.4.1.

So I'm about to use the package on im.com (downloads > beta versions), and re-apply our changes (git can do that). Should be best :-).

**Pull request closed without merging**
